version: '3.1'

services:

  db:
    image: mongo:4.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "t3st3b1tX"
      MONGO_INITDB_DATABASE: "teste-bitx"
    ports:
      - "27017:27017"